export { default as Home } from './Home'
export { default as Leads } from './Login'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Registration } from './Registration'
